{% set name = "hydrampp" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/raw-lab/HydraMPP/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 04dc702b1282a04718764cf9ba9068fa9585857a58e3ec894a37d72176501b09

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - setuptools
    - psutil

test:
  imports:
    - hydraMPP
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/raw-lab/HydraMPP
  summary: A simple yet powerfull library for Distributed Computing
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - decrevi
